name: Ask a question
description: Ask any questions you want to ask
title: "[QUESTION] Short title of your question"
labels: [question]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! Explain the questions you want as clearly as possible
  - type: textarea
    id: question
    attributes:
      label: What do you want to ask?
      placeholder: Explain what you want to ask
    validations:
      required: true